### PR TITLE
Adds support for the kubernetes-based scraper deployment

### PR DESCRIPTION
**Pull request by pboothe**
Added support for generating kubernetes configs, and also tests of the same.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/operator/78)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[plsync/mlabconfig.py, line 481 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kct7n2qsRLF2xt_01aB:-Kct7n2qsRLF2xt_01aC:b-by66js) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L481)):*
> ```Python
>     configs = []
>     for experiment in experiments:
>         slice_name = experiment['name']
> ```

Due to the punctuation substitution at line 492, this will change slice names of the form "iupui_ndt" into "iupui-ndt". So we don't create a third way of representing experiment names, what do you think of using the `experiment.dnsname()` instead? This would return `ndt.iupui`. Also, could we eliminate punctuation substitution since nodes and sites should not have any, and it appears that "." are okay for kubernetes metadata names?

https://github.com/m-lab/operator/blob/master/plsync/planetlab/model.py#L576

There is a slightly longer conversation to have offline about how to change our terminology from the old world to the new world. This file is steeped in the old world atm.

---

*[plsync/mlabconfig.py, line 486 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kcsu7CoHzBIP8003Tco:-Kcsu7CoHzBIP8003Tcp:b1rm2ru) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L486)):*
> ```Python
>             if experiment['index'] is None:
>                 continue
>             rsync_host = experiment.hostname(node)
> ```

I don't remember what the content of 'network_list' is. Is "name" an incomplete hostname? (i.e. can we use `rsync_host` as the loop variable and eliminate this call to `experiment.hostname`?

---

*[plsync/mlabconfig.py, line 492 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kct4DhHt22ILSpxvtbL:-Kct4DhIdI5O5E-A2RFr:b-r23i1z) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L492)):*
> ```Python
>                           'experiment': slice_name}
>                 for k in config.keys():
>                     config[k] = re.sub(r'[^a-zA-Z0-9]+', '-', config[k])
> ```

I had to parse this. Would you be willing to add a comment saying something like this? "replace all punctuation with a hyphen."

---

*[plsync/mlabconfig.py, line 528 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-KcsY3IXR7Fo4Z9Ewjqr:-KcsY3IXR7Fo4Z9Ewjqs:b-7m1kgq) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L528)):*
> ```Python
>             sys.stdout.write("\n\n")
>             export_mlab_zone_records(sys.stdout, sites, experiments)
>     elif options.format == 'scraper_kubernetes':
> ```

Would you be willing to update the `usage` function with an example of this command?

---

*[plsync/mlabconfig_test.py, line 367 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kct6BuIbRmFujkW_ejh:-Kct6BuJgFuGbplrS11z:b8uk932) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig_test.py#L367)):*
> ```Python
>         for hostname, node in self.sites[0]['nodes'].iteritems():
>             experiments[0].add_node_address(node)
>         template = textwrap.dedent("""\
> ```

TIL: `textwrap.dedent` is a thing.

---

*[plsync/slices.py, line 148 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-KcsXD6BSzOuuMZ7lef1:-KcsXD6Cw9_giO_9AgaW:b-tngn4t) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/slices.py#L148)):*
> ```Python
>                                             use_initscript=True,
>                                             ipv6="all",
>                                             rsync_modules=['utilization']),
> ```

mlab_utility also exports the "switch" rsyncd module for disco data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/78)*

**Comment by pboothe** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[plsync/mlabconfig.py, line 481 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kct7n2qsRLF2xt_01aB:-KctFOyHJXRJcsDV0gq8:b-e6g66o) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L481)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Due to the punctuation substitution at line 492, this will change slice names of the form "iupui_ndt" into "iupui-ndt". So we don't create a third way of representing experiment names, what do you think of using the `experiment.dnsname()` instead? This would return `ndt.iupui`. Also, could we eliminate punctuation substitution since nodes and sites should not have any, and it appears that "." are okay for kubernetes metadata names?

https://github.com/m-lab/operator/blob/master/plsync/planetlab/model.py#L576

There is a slightly longer conversation to have offline about how to change our terminology from the old world to the new world. This file is steeped in the old world atm.
</blockquote></details>

This breaks the names of my jobs which all look like:
`{site}-{node}-{experiment}-{rsync_module}`, for example `acc02-mlab2-iupui-npad-sidestream`.  When I make the change to use `.dnsname()`, they become `acc02-mlab2-npad.iupui-sidestream` which seems worse. 

Resolved offline: we'll leave it like it is, but we'll also all feel bad about how hostnames are designed to be least-significant-bit-first and that makes sorting of them terrible.

---

*[plsync/mlabconfig.py, line 486 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kcsu7CoHzBIP8003Tco:-KctGN-hvlWqvT-DKkiM:b1w2pxs) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L486)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't remember what the content of 'network_list' is. Is "name" an incomplete hostname? (i.e. can we use `rsync_host` as the loop variable and eliminate this call to `experiment.hostname`?
</blockquote></details>

`name` is e.g. `mlab3.lga0t.measurement-lab.org`, but `rsync_host` is e.g. `ndt.iupui.mlab3.lga0t.measurement-lab.org`

That is, it appeared to me that `name` was the node name and then `experiment.hostname` decorated that name to include the particular experiment.

---

*[plsync/mlabconfig.py, line 492 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kct4DhHt22ILSpxvtbL:-KctJFa0hm9QqFSs7J8_:b-du4ycd) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L492)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I had to parse this. Would you be willing to add a comment saying something like this? "replace all punctuation with a hyphen."
</blockquote></details>

Added an explanation.

---

*[plsync/mlabconfig.py, line 528 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-KcsY3IXR7Fo4Z9Ewjqr:-KctK5XfeoGixfEO_MHD:b-896fix) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L528)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Would you be willing to update the `usage` function with an example of this command?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/78)*

**Comment by pboothe** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[plsync/slices.py, line 148 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-KcsXD6BSzOuuMZ7lef1:-KctKX1uYJkBKOyT9RXY:b-896fix) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/slices.py#L148)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

mlab_utility also exports the "switch" rsyncd module for disco data.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/78)*

**Comment by pboothe** [comment]
PTAL

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[plsync/mlabconfig.py, line 486 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kcsu7CoHzBIP8003Tco:-KctO3t2x-t7k7Wvlx60:b-eztjv5) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L486)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`name` is e.g. `mlab3.lga0t.measurement-lab.org`, but `rsync_host` is e.g. `ndt.iupui.mlab3.lga0t.measurement-lab.org`

That is, it appeared to me that `name` was the node name and then `experiment.hostname` decorated that name to include the particular experiment.
</blockquote></details>

Okay. LGTM.

---

*[plsync/mlabconfig.py, line 492 at r1](https://reviewable.io:443/reviews/m-lab/operator/78#-Kct4DhHt22ILSpxvtbL:-KctOZS6htpx6TJLQGn7:b-9755fn) ([raw file](https://github.com/m-lab/operator/blob/a655616f4b1315530f9fd2d1811eaff3e72d6bac/plsync/mlabconfig.py#L492)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Added an explanation.
</blockquote></details>

Thank you!

---

*[plsync/mlabconfig.py, line 486 at r4](https://reviewable.io:443/reviews/m-lab/operator/78#-KctOirSGSlYM_6RvkFX:-KctOirSGSlYM_6RvkFY:b-bu3969) ([raw file](https://github.com/m-lab/operator/blob/a0bb6faf8aff9d1e6af44382c8d71858c3ad04a5/plsync/mlabconfig.py#L486)):*
> ```Python
>         slice_name = experiment['name']
>         for name, node in experiment['network_list']:
>             print 'NAME', name
> ```

These print statements look vestigial (and "RSYNC_HOST" below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/78#-:-KctOoMNVfveXhTrRbuc:bnfp4nl)*

**Comment by pboothe** [comment]
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[plsync/mlabconfig.py, line 486 at r4](https://reviewable.io:443/reviews/m-lab/operator/78#-KctOirSGSlYM_6RvkFX:-KctS6Pf1JCnD06w2_JB:b-igcsp2) ([raw file](https://github.com/m-lab/operator/blob/a0bb6faf8aff9d1e6af44382c8d71858c3ad04a5/plsync/mlabconfig.py#L486)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

These print statements look vestigial (and "RSYNC_HOST" below.)
</blockquote></details>

Good eye. Deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/78)*

**Pull request merged**
