### PR TITLE
Adds more names to the template possibilities.

### PR DESCRIPTION
**Pull request by pboothe**
Also allows users to choose "safe" values or potentially unsafe values,
as desired.  Safe values have only letters, numbers or dashes. Unsafe
values may have dots or underscores or anything else that the config
generates.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/operator/102)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
:lgtm: with suggested changes.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[plsync/mlabconfig.py, line 512 at r1](https://reviewable.io:443/reviews/m-lab/operator/102#-KjxQuKQs-WTuu7T-h2C:-KjxQuKQs-WTuu7T-h2D:b-mr0u5o) ([raw file](https://github.com/m-lab/operator/blob/e275861ff707467b4445cd7ed34e35d381bd9e93/plsync/mlabconfig.py#L512)):*
> ```Python
>                 continue
>             for rsync_module in experiment['rsync_modules']:
>                 config = {'full_nodename': name,
> ```

s/full_nodename/machine/g

Also, does `name == node.hostname()`?

---

*[plsync/mlabconfig.py, line 515 at r1](https://reviewable.io:443/reviews/m-lab/operator/102#-KjxRsmqVArVY2YDvZf_:-KjxRsmqVArVY2YDvZfa:b-h1kx7w) ([raw file](https://github.com/m-lab/operator/blob/e275861ff707467b4445cd7ed34e35d381bd9e93/plsync/mlabconfig.py#L515)):*
> ```Python
>                           'site': site_name,
>                           'node': node_name,
>                           'experiment': slice_name,
> ```

Please use the same convention as PR #101.

```
labels['experiment'] = experiment.dnsname()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/102#-:-KjxSjLhT7KPqbYhJenZ:bfnfipf)*

**Comment by pboothe** [comment]
The changes got a little big. Would you mind double-checking?

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[plsync/mlabconfig.py, line 518 at r2](https://reviewable.io:443/reviews/m-lab/operator/102#-KjxfowflukxdzFsLx9T:-KjxfowflukxdzFsLx9U:bsrw62l) ([raw file](https://github.com/m-lab/operator/blob/d14e1e8d65a671f103282fcbaef62075a2d4eb1a/plsync/mlabconfig.py#L518)):*
> ```Python
>                           'rsync_module': rsync_module,
>                           'rsync_host': rsync_host}
>                 for key, value in list(config.items()):
> ```

Is `list` necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/102#-:-KjxgNZF54piqDmSIpnw:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/102)*

**Comment by pboothe** [comment]
*[plsync/mlabconfig.py, line 518 at r2](https://reviewable.io:443/reviews/m-lab/operator/102#-KjxfowflukxdzFsLx9T:-KjxiQft1yrSSZ-_3Ahv:b-ahahok) ([raw file](https://github.com/m-lab/operator/blob/d14e1e8d65a671f103282fcbaef62075a2d4eb1a/plsync/mlabconfig.py#L518)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is `list` necessary?
</blockquote></details>

Maybe? `config.items()` may be a generator, and if it is, then changing what is stored in the hashtable will cause everything to crash.  It's defensive programming to ensure that I don't have to think about whether altering the hashtable will cause the iteration to crash.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/102)*

**Comment by pboothe** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[plsync/mlabconfig.py, line 512 at r1](https://reviewable.io:443/reviews/m-lab/operator/102#-KjxQuKQs-WTuu7T-h2C:-KjxiQ6oYo1prne-XYEo:b-896fix) ([raw file](https://github.com/m-lab/operator/blob/e275861ff707467b4445cd7ed34e35d381bd9e93/plsync/mlabconfig.py#L512)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/full_nodename/machine/g

Also, does `name == node.hostname()`?
</blockquote></details>

Done.

---

*[plsync/mlabconfig.py, line 515 at r1](https://reviewable.io:443/reviews/m-lab/operator/102#-KjxRsmqVArVY2YDvZf_:-KjxiQSFbKLtrxnm191J:b-896fix) ([raw file](https://github.com/m-lab/operator/blob/e275861ff707467b4445cd7ed34e35d381bd9e93/plsync/mlabconfig.py#L515)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use the same convention as PR #101.

```
labels['experiment'] = experiment.dnsname()
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/102)*

**Pull request merged**
