### PR TITLE
Add new sites FRA01-04

### PR DESCRIPTION
**Pull request by critzo**
This commit adds four new mlab pods to sites.py in preparation for their upcoming roll-out. @jheretic or @nkinkade could you PTAL?

### CODE REVIEW

**Comment by critzo** [comment]
Thanks @jheretic -- My latest commit addresses this, and a prior entry for MAD04. PTAL?

**Comment by critzo** [comment]
@nkinkade Could you PTAL at this PR to add FRA01-04 ? Thanks.

**Comment by nkinkade** [comment]
@critzo: two small questions:

1) The lat/lon for fra{1,2,3,4} are specified to 7 decimal places, while almost all the others in the file are to only 6 places. This shouldn't matter, but a long time ago Jordan had [made a comment in the deployment document](https://docs.google.com/document/d/1pgrRyIA9F82RKC3CnSq30y-rRZI1QizzU6HmBtMBww4/edit#heading=h.c7y6z1b0n416) that it should only be specified to 4 places, else PLC would choke on it. This clearly isn't right, but it has had me wondering about it.

2) Should mad04 have an arch type of `x86_64-r630`?

**Comment by critzo** [comment]
Thanks @nkinkade - I reduced the lat/lon to 6 decimal places and corrected the arch tag for the new MAD pods. PTAL?

**Comment by nkinkade** [comment]
@critzo: LGTM, with one tiny nit about the indention of the city for fra02.  Thanks!

**Pull request merged**
