### PR TITLE
Add metadata directory and metadata deploy step

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new file containing user authorize_keys files.

This change also creates a directory structure to mimic a metadata service api for static data served from GCS.

For example, the authorized_keys file could be accessed by build scripts or startup scripts at:
https://storage.googleapis.com/operator-mlab-sandbox/metadata/v0/users/authorized_keys

The thinking is that for static content, e.g. lists of servers, slices, IP whitelists, these could be generated statically and uploaded to a structured location that could be referenced by other services. This is functionally equivalent to what a metadata service could ultimately provide but much lighter weight.

The initial version is "v0" to indicate this is in a trial phase.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/operator/183)

### CODE REVIEW

**Comment by nkinkade** [comment]
Two small comments.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 57 at r1](https://reviewable.io:443/reviews/m-lab/operator/183#-L308SbXDzVk9apF4_G0:-L308SbXDzVk9apF4_G1:bo2ophj) ([raw file](https://github.com/m-lab/operator/blob/2da2497ac8ab723aaf16af0766b7953704dc4642/.travis.yml#L57)):*
> ```YAML
> - provider: script
>   script: $TRAVIS_BUILD_DIR/travis/deploy_gcs.sh SERVICE_ACCOUNT_mlab_sandbox
>       $TRAVIS_BUILD_DIR/metadata/v0 gs://epoxy-mlab-sandbox/metadata/
> ```

You comment for the PR mentions possibly accessing this in the `operator-mlab-sandbox` GCS bucket. Do you mean to be copying this to `epoxy-mlab-sandbox`?

---

*[.travis.yml, line 58 at r1](https://reviewable.io:443/reviews/m-lab/operator/183#-L308c4uA53UxD-CgD7_:-L308c4uA53UxD-CgD7a:b80w6on) ([raw file](https://github.com/m-lab/operator/blob/2da2497ac8ab723aaf16af0766b7953704dc4642/.travis.yml#L58)):*
> ```YAML
>   script: $TRAVIS_BUILD_DIR/travis/deploy_gcs.sh SERVICE_ACCOUNT_mlab_sandbox
>       $TRAVIS_BUILD_DIR/metadata/v0 gs://epoxy-mlab-sandbox/metadata/
>   skip_cleanup: true
> ```

Is `skip_cleanup` needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/183#-:-L309fLz33vzXWOeMTUM:b-z0tvc)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 57 at r1](https://reviewable.io:443/reviews/m-lab/operator/183#-L308SbXDzVk9apF4_G0:-L30AH8ntQyJeOZkLnOR:b-1uyvt3) ([raw file](https://github.com/m-lab/operator/blob/2da2497ac8ab723aaf16af0766b7953704dc4642/.travis.yml#L57)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

You comment for the PR mentions possibly accessing this in the `operator-mlab-sandbox` GCS bucket. Do you mean to be copying this to `epoxy-mlab-sandbox`?
</blockquote></details>

Yes! Thank you for catching that :D

---

*[.travis.yml, line 58 at r1](https://reviewable.io:443/reviews/m-lab/operator/183#-L308c4uA53UxD-CgD7_:-L30AKDIJ8S8Wni-PoFC:by450f) ([raw file](https://github.com/m-lab/operator/blob/2da2497ac8ab723aaf16af0766b7953704dc4642/.travis.yml#L58)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is `skip_cleanup` needed?
</blockquote></details>

I wondered about this too. I don't know what happens if one deploy target sets this to true but another does not. So, I erred on the side of caution. I could remove this and we could see if it breaks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/183)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 58 at r1](https://reviewable.io:443/reviews/m-lab/operator/183#-L308c4uA53UxD-CgD7_:-L30AmG5PefMRUqT6tIL:b-7fkuc8) ([raw file](https://github.com/m-lab/operator/blob/2da2497ac8ab723aaf16af0766b7953704dc4642/.travis.yml#L58)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I wondered about this too. I don't know what happens if one deploy target sets this to true but another does not. So, I erred on the side of caution. I could remove this and we could see if it breaks?
</blockquote></details>

I don't think there is any harm in leaving this, so if there is even a tiny bit of doubt, then I'd just leave it. I only mentioned it with any eye toward being minimal and removing things that weren't strictly necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/183#-:-L30B1nhJacLSCTg1VmF:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[.travis.yml, line 58 at r1](https://reviewable.io:443/reviews/m-lab/operator/183#-L308c4uA53UxD-CgD7_:-L30BQUCNf5bvsOUBfU8:b6z5z75) ([raw file](https://github.com/m-lab/operator/blob/2da2497ac8ab723aaf16af0766b7953704dc4642/.travis.yml#L58)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I don't think there is any harm in leaving this, so if there is even a tiny bit of doubt, then I'd just leave it. I only mentioned it with any eye toward being minimal and removing things that weren't strictly necessary.
</blockquote></details>

I tend to agree with keeping the configs as minimal as possible. Generally I think there's an expectation that if we've written a thing in a config that it's necessary or important for some reason that's different from the default value. And, if that's not the case, I think it's preferable to rely on the defaults when possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/183)*

**Comment by stephen-soltesz** [comment]
Travis builds are having a bad day. Merging anyway.

**Pull request merged**
