### PR TITLE
Add --node-key-keep option to plsync.

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new flag to plsync to keep the node key while generating new boot images. This is helpful for creating new boot images prior to upgrading an existing site without breaking the current deployment.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/operator/86)

### CODE REVIEW

**Comment by salarcon215** [comment]
Two small notes about help message text, but other than that, I've tested it with an existing site and it LGTM. Thank you!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[plsync/plsync.py, line 24 at r1](https://reviewable.io:443/reviews/m-lab/operator/86#-Kfmw__UZzvzOTRSlERJ:-Kfmw__V7wdiOcfr9j9z:b-gjs3ev) ([raw file](https://github.com/m-lab/operator/blob/377e4a6752eb4a76372c4fd5349c324269182183/plsync/plsync.py#L24)):*
> ```Python
>                 create site, nodes, PCUs and configuration.  As well, this
>                 command downloads the boot images for the new site to PWD.
>                 Downloading the boot image should occur *only once*.  Every
> ```

No longer true in all cases, yay! Could you update the help text? Does it make sense to add "unless used with the --node-key-keep option"?

---

*[plsync/plsync.py, line 176 at r1](https://reviewable.io:443/reviews/m-lab/operator/86#-KfmxADd4nju-abMRhuq:-KfmxADepVtBt96rPg2Q:b-xdcpat) ([raw file](https://github.com/m-lab/operator/blob/377e4a6752eb4a76372c4fd5349c324269182183/plsync/plsync.py#L176)):*
> ```Python
>                 help=("download the ISO boot images for Nodes. This is a"+
>                       " destructive operation if ISOs have previously been "+
>                       "downloaded."))
> ```

A similar note here. Does it make sense to add "unless used with the --node-key-keep option"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/86#-:-KfmxWlX6Dt_1uy7gEiw:b-khc5fa)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[plsync/plsync.py, line 24 at r1](https://reviewable.io:443/reviews/m-lab/operator/86#-Kfmw__UZzvzOTRSlERJ:-KfnCDW5lowgxwY0Pi5W:b-e0luc9) ([raw file](https://github.com/m-lab/operator/blob/377e4a6752eb4a76372c4fd5349c324269182183/plsync/plsync.py#L24)):*
<details><summary><i>Previously, salarcon215 wrote…</i></summary><blockquote>

No longer true in all cases, yay! Could you update the help text? Does it make sense to add "unless used with the --node-key-keep option"?
</blockquote></details>

Good point. I've updated the help text. How does it look?

---

*[plsync/plsync.py, line 176 at r1](https://reviewable.io:443/reviews/m-lab/operator/86#-KfmxADd4nju-abMRhuq:-KfnCndESEQb4y3g4-_4:bc6eeuz) ([raw file](https://github.com/m-lab/operator/blob/377e4a6752eb4a76372c4fd5349c324269182183/plsync/plsync.py#L176)):*
<details><summary><i>Previously, salarcon215 wrote…</i></summary><blockquote>

A similar note here. Does it make sense to add "unless used with the --node-key-keep option"?
</blockquote></details>

Good catch, how does it look now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/86)*

**Comment by salarcon215** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[plsync/plsync.py, line 24 at r1](https://reviewable.io:443/reviews/m-lab/operator/86#-Kfmw__UZzvzOTRSlERJ:-KfnLQs51pgUiNIYBgHf:bdkiwka) ([raw file](https://github.com/m-lab/operator/blob/377e4a6752eb4a76372c4fd5349c324269182183/plsync/plsync.py#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Good point. I've updated the help text. How does it look?
</blockquote></details>

Looks good, thank you!

---

*[plsync/plsync.py, line 176 at r1](https://reviewable.io:443/reviews/m-lab/operator/86#-KfmxADd4nju-abMRhuq:-KfnMA_y04pxALTooMMp:btojbfd) ([raw file](https://github.com/m-lab/operator/blob/377e4a6752eb4a76372c4fd5349c324269182183/plsync/plsync.py#L176)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Good catch, how does it look now?
</blockquote></details>

Great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/86)*

**Comment by salarcon215** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/86)*

**Pull request merged**
