### PR TITLE
Generates IPv6 targets for mobiperf and neubot.

### PR DESCRIPTION
**Pull request by nkinkade**
This PR causes *generate_prometheus_targets.sh* to generate IPv6 targets for mobiperf and neubot. This PR is complementary to m-lab/prometheus-support#198

This change is [Reviewable](https://reviewable.io/reviews/m-lab/operator/205)

### CODE REVIEW

**Comment by nkinkade** [comment]
I've added another commit which also generates IPv6 targets for the ssh806 service. This was at the request of @mattmathis so that we'd have a way of checking IPv6 connectivity at a site that was independent of experiments.

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[generate_prometheus_targets.sh, line 52 at r1](https://reviewable.io:443/reviews/m-lab/operator/205#-L7eMfzjk21pVPlCX9lN:-L7eMfzkBppjmOxzwg0l:birrja3) ([raw file](https://github.com/m-lab/operator/blob/e48522a062c898f09ba8a5f68066d9d690d5b039/generate_prometheus_targets.sh#L52)):*
> ```Shell
>       ./mlabconfig.py --format=prom-targets-nodes \
>           --template_target={{hostname}}:806 \
>           --label service=ssh806 \
> ```

Do we want to distinguish the v4/v6 service names?

Will it be helpful to use a pattern like `<name>_<addr_family>`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/operator/205#-:-L7eN0QaSKb1bLsHSpoc:bnfp4nl)*

**Comment by nkinkade** [comment]
I forgot that GCP doesn't really support IPv6  (except on Load Balancers). In light of that, this PR doesn't make any sense. :(

**Comment by nkinkade** [comment]
I'm reopening this PR, along with a few new changes and one bug fix.

**Comment by nkinkade** [comment]
Ooops... this won't let me reopen this because I force-pushed my fork branch. I'll open a new one.

**Pull request closed without merging**
